name: Build Docker Images

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile]
        directory: [system]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Get changed files
      id: getfile
      run: |
        echo "Current SHA: ${{ github.sha }}"
        echo "Previous SHA: ${{ github.event.before }}"
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)
        echo "Changed files: $changed_files"
        echo "changed_files=$changed_files" >> $GITHUB_ENV
      shell: bash

    - name: Echo output
      run: |
        echo $changed_files

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./${{ matrix.directory }}
        file: ./${{ matrix.directory }}/${{ matrix.dockerfile }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/app:latest
